# Generated by Django 5.0.6 on 2025-10-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_userprofile_trade_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trading_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
